services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_DOMAIN: http://localhost:1337
      NEXT_PUBLIC_STRAPI_API_URL: http://localhost:1337/api
      NEXT_PUBLIC_STRAPI_API_TOKEN: af4052801098d716bb683b3eea294bb4dbea0259a64bfe7761d46dc56bc2414bc198598161384a49ab900d1a09d938bec1f46755561b08b9dedef144c2fea7b1d4e972d840c2f36b32a7c6f460942205a672129c6c8bd4a8b8e20cffef35401f45f70b175e5f9b3e765a615a670976f38be763d94227b55f669a80bd488c768a
      NEXT_PUBLIC_PAGE_LIMIT: 10
      WATCHPACK_POLLING: true
      CHOKIDAR_USEPOLLING: true
    extra_hosts:
      - "localhost:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
